//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellurian.Trains.Models.Planning.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tellurian.Trains.Models.Planning.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} arrival {1} is after departure {2}..
        /// </summary>
        internal static string ArrivalIsAfterDeparture {
            get {
                return ResourceManager.GetString("ArrivalIsAfterDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train {0} {1} has conflicts with train {2} {3}..
        /// </summary>
        internal static string CallAtStationHasConflictsWithOtherCall {
            get {
                return ResourceManager.GetString("CallAtStationHasConflictsWithOtherCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {0} track {1} arr {2} dep {3}.
        /// </summary>
        internal static string CallAtStationTrackDuringTimes {
            get {
                return ResourceManager.GetString("CallAtStationTrackDuringTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call {0} must be after previous call {1} for train {2}..
        /// </summary>
        internal static string CallMustBeAfterPreviousCall {
            get {
                return ResourceManager.GetString("CallMustBeAfterPreviousCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict on stretch {0} between {1} and {2}..
        /// </summary>
        internal static string ConflictOnStretchBetweenPassingTrains {
            get {
                return ResourceManager.GetString("ConflictOnStretchBetweenPassingTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate add of station {0}..
        /// </summary>
        internal static string DuplicateAddOfStation {
            get {
                return ResourceManager.GetString("DuplicateAddOfStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate train number {0} in loco schedule {1}..
        /// </summary>
        internal static string DuplicateTrainInLocoSchedule {
            get {
                return ResourceManager.GetString("DuplicateTrainInLocoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A loco schedule must have an identity..
        /// </summary>
        internal static string LocoScheduleMustHaveAnIdentity {
            get {
                return ResourceManager.GetString("LocoScheduleMustHaveAnIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length is 5 characters..
        /// </summary>
        internal static string MaxLengthIs5 {
            get {
                return ResourceManager.GetString("MaxLengthIs5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length is 50 characters..
        /// </summary>
        internal static string MaxLengthIs50 {
            get {
                return ResourceManager.GetString("MaxLengthIs50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one stretch between {0} and {1}..
        /// </summary>
        internal static string MoreThanOneStretchBetweenStations {
            get {
                return ResourceManager.GetString("MoreThanOneStretchBetweenStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of {0} is required..
        /// </summary>
        internal static string NameOfObjectIsRequired {
            get {
                return ResourceManager.GetString("NameOfObjectIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is missing..
        /// </summary>
        internal static string NoValue {
            get {
                return ResourceManager.GetString("NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of {0} is required..
        /// </summary>
        internal static string NumberOfObjectIsRequired {
            get {
                return ResourceManager.GetString("NumberOfObjectIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature of {0} is required..
        /// </summary>
        internal static string SignatureOfObjectIsRequired {
            get {
                return ResourceManager.GetString("SignatureOfObjectIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature of station is required..
        /// </summary>
        internal static string SignatureOfStationIsRequired {
            get {
                return ResourceManager.GetString("SignatureOfStationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station exit {0} is not in layout..
        /// </summary>
        internal static string StationExitIsNotInLayout {
            get {
                return ResourceManager.GetString("StationExitIsNotInLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station {0} has no track number {1}..
        /// </summary>
        internal static string StationHasNotTrackNumber {
            get {
                return ResourceManager.GetString("StationHasNotTrackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch may not start and end at the same station exit..
        /// </summary>
        internal static string StretchMayNotStartAndEndAtSameStationExit {
            get {
                return ResourceManager.GetString("StretchMayNotStartAndEndAtSameStationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stretch may not start and end at the same station {0}..
        /// </summary>
        internal static string StretchMayNotStartAndEndAtTheSameStation {
            get {
                return ResourceManager.GetString("StretchMayNotStartAndEndAtTheSameStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        internal static string StretchToString {
            get {
                return ResourceManager.GetString("StretchToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no from-station with signature or name {0}..
        /// </summary>
        internal static string ThereIsNoFromStationWithSignatureOrName {
            get {
                return ResourceManager.GetString("ThereIsNoFromStationWithSignatureOrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no station with name or signature {0}..
        /// </summary>
        internal static string ThereIsNoStationWithNameOrSignature {
            get {
                return ResourceManager.GetString("ThereIsNoStationWithNameOrSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no stretch between {0} and {1}..
        /// </summary>
        internal static string ThereIsNoStretchBetweenStation1AndStation2 {
            get {
                return ResourceManager.GetString("ThereIsNoStretchBetweenStation1AndStation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no to-station with signature or name {0}..
        /// </summary>
        internal static string ThereIsNoToStationWithSignatureOrName {
            get {
                return ResourceManager.GetString("ThereIsNoToStationWithSignatureOrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The station {0} is not part of the timetable stretch..
        /// </summary>
        internal static string TheStationNameIsNotPartOfTheStretch {
            get {
                return ResourceManager.GetString("TheStationNameIsNotPartOfTheStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable stretch.
        /// </summary>
        internal static string TimetableStretch {
            get {
                return ResourceManager.GetString("TimetableStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track {0} in station {1} referred in train {2} is not in layout..
        /// </summary>
        internal static string TrackInStationReferredInTrainIsNotInLayout {
            get {
                return ResourceManager.GetString("TrackInStationReferredInTrainIsNotInLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track {0} in station {1} is occupied by train {2} during {3}..
        /// </summary>
        internal static string TrackIsOccupiedByTrainBetween {
            get {
                return ResourceManager.GetString("TrackIsOccupiedByTrainBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track stretch is already assigned to exit {0} at station {1}..
        /// </summary>
        internal static string TrackStretchIsAlreadyAssignedToExitNameAtStationName {
            get {
                return ResourceManager.GetString("TrackStretchIsAlreadyAssignedToExitNameAtStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train {0} between {1} is conflicting with train {2} between {3}..
        /// </summary>
        internal static string TrainBetweenPassingIsConflictingWithTrainBetweenPassing {
            get {
                return ResourceManager.GetString("TrainBetweenPassingIsConflictingWithTrainBetweenPassing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train {0} calls {1} and {2} are conflicting..
        /// </summary>
        internal static string TrainHasConflictingCalls {
            get {
                return ResourceManager.GetString("TrainHasConflictingCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train {0} must stop at at least two stations..
        /// </summary>
        internal static string TrainMustHaveMinimumTwoCalls {
            get {
                return ResourceManager.GetString("TrainMustHaveMinimumTwoCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train {0} speed from {1} {2} to {3} {4} is too fast, length {5:F1} meters..
        /// </summary>
        internal static string TrainSpeedBetweenCallsIsTooFast {
            get {
                return ResourceManager.GetString("TrainSpeedBetweenCallsIsTooFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train {0} speed from {1} {2} to {3} {4} is too slow, length {5:F1} meters..
        /// </summary>
        internal static string TrainSpeedBetweenCallsIsTooSlow {
            get {
                return ResourceManager.GetString("TrainSpeedBetweenCallsIsTooSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle schedule {0} contains overlapping {1} and {2}..
        /// </summary>
        internal static string VehicleScheduleContainsOverlappingTrainParts {
            get {
                return ResourceManager.GetString("VehicleScheduleContainsOverlappingTrainParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
