//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellurian.Trains.Repositories.Xpln.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tellurian.Trains.Repositories.Xpln.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival to station {0} not found for train {1} in loco schedule &apos;{2}&apos; at {3}&quot;).
        /// </summary>
        internal static string ArrivatToStationNotFoundForTrainInLocoScheduleAtTime {
            get {
                return ResourceManager.GetString("ArrivatToStationNotFoundForTrainInLocoScheduleAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read schedule due to errors in timetable..
        /// </summary>
        internal static string CannotReadScheduleDueToErrorsInTimetable {
            get {
                return ResourceManager.GetString("CannotReadScheduleDueToErrorsInTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read timetable due to errors in layout..
        /// </summary>
        internal static string CannotReadTimetableDueToErrorsInLayout {
            get {
                return ResourceManager.GetString("CannotReadTimetableDueToErrorsInLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure from station {0} not found for train {1} in loco schedule &apos;{2}&apos; at {3}&quot;).
        /// </summary>
        internal static string DepartureFromStationNotFoundForTrainInLocoScheduleAtTime {
            get {
                return ResourceManager.GetString("DepartureFromStationNotFoundForTrainInLocoScheduleAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature {0} is not supported..
        /// </summary>
        internal static string FeatureIsNotSupported {
            get {
                return ResourceManager.GetString("FeatureIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco {0} at station {1} with arrival {2} refers to a nonexisting time in train {3}..
        /// </summary>
        internal static string LocoAtStationWithArrivalDoNotRefersToAnExistingTimeInTrain {
            get {
                return ResourceManager.GetString("LocoAtStationWithArrivalDoNotRefersToAnExistingTimeInTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco {0} at station {1} with departure {2} refers to a nonexisting time in train {3}..
        /// </summary>
        internal static string LocoAtStationWithDepartureDoNotRefersToAnExistingTimeInTrain {
            get {
                return ResourceManager.GetString("LocoAtStationWithDepartureDoNotRefersToAnExistingTimeInTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco {0} in train {1} has wrong timing. Arrival {2} is before departure {3}..
        /// </summary>
        internal static string LocoInTrainHasWrongTimingEndStartionIsBeforeStartStation {
            get {
                return ResourceManager.GetString("LocoInTrainHasWrongTimingEndStartionIsBeforeStartStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no station with signature or name &apos;{0}&apos;..
        /// </summary>
        internal static string ThereIsNoStationWithSignatureOrName {
            get {
                return ResourceManager.GetString("ThereIsNoStationWithSignatureOrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train {0} at {1} arr {2} dep {3} referens to a nonexisting track {4}..
        /// </summary>
        internal static string TrainAtStationAtTimeRefersToANonexistingTrack {
            get {
                return ResourceManager.GetString("TrainAtStationAtTimeRefersToANonexistingTrack", resourceCulture);
            }
        }
    }
}
