//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetablePlanning.Importers.Xpln.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimetablePlanning.Importers.Xpln.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read schedule due to errors in timetable..
        /// </summary>
        internal static string CannotReadScheduleDueToErrorsInTimetable {
            get {
                return ResourceManager.GetString("CannotReadScheduleDueToErrorsInTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read timetable due to errors in layout..
        /// </summary>
        internal static string CannotReadTimetableDueToErrorsInLayout {
            get {
                return ResourceManager.GetString("CannotReadTimetableDueToErrorsInLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Column {1} is not specified..
        /// </summary>
        internal static string ColumnIsNotSpecified {
            get {
                return ResourceManager.GetString("ColumnIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Column {1} must contain a number, current value is {2}..
        /// </summary>
        internal static string ColumnMustBeANumber {
            get {
                return ResourceManager.GetString("ColumnMustBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Column {1} must be a time, current value is {2}..
        /// </summary>
        internal static string ColumnMustBeATime {
            get {
                return ResourceManager.GetString("ColumnMustBeATime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Column {1} must contain a value..
        /// </summary>
        internal static string ColumnMustHaveAValue {
            get {
                return ResourceManager.GetString("ColumnMustHaveAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature {0} is not supported..
        /// </summary>
        internal static string FeatureIsNotSupported {
            get {
                return ResourceManager.GetString("FeatureIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Not all fields present, expected count is {1}, actual count is {2}..
        /// </summary>
        internal static string NotAllFieldsArePresent {
            get {
                return ResourceManager.GetString("NotAllFieldsArePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Object &apos;{1}&apos; at station {2} with arrival {3} refers to a non existing time in train {4}..
        /// </summary>
        internal static string ObjectAtStationWithArrivalDoNotRefersToAnExistingTimeInTrain {
            get {
                return ResourceManager.GetString("ObjectAtStationWithArrivalDoNotRefersToAnExistingTimeInTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Object &apos;{1}&apos; at station {2} with departure {3} refers to a non existing time in train {4}..
        /// </summary>
        internal static string ObjectAtStationWithDepartureDoNotRefersToAnExistingTimeInTrain {
            get {
                return ResourceManager.GetString("ObjectAtStationWithDepartureDoNotRefersToAnExistingTimeInTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Object &apos;{1}&apos; in train {2} has wrong timing. Departure {3} is before arrival {4}..
        /// </summary>
        internal static string ObjectInTrainHasWrongTimingEndStartionIsBeforeStartStation {
            get {
                return ResourceManager.GetString("ObjectInTrainHasWrongTimingEndStartionIsBeforeStartStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading worksheet {0}....
        /// </summary>
        internal static string ReadingWorksheet {
            get {
                return ResourceManager.GetString("ReadingWorksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Route &apos;{1}&apos; not found in current layout..
        /// </summary>
        internal static string RouteNotFoundInLayout {
            get {
                return ResourceManager.GetString("RouteNotFoundInLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Route number missing, using default &apos;{1}&apos;..
        /// </summary>
        internal static string RouteNumberIsMissingUsingDefault {
            get {
                return ResourceManager.GetString("RouteNumberIsMissingUsingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: {1}..
        /// </summary>
        internal static string RowMessage {
            get {
                return ResourceManager.GetString("RowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Station &apos;{1}&apos; not found in current layout..
        /// </summary>
        internal static string StationNotFoundInLayout {
            get {
                return ResourceManager.GetString("StationNotFoundInLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no station &apos;{0}&apos;..
        /// </summary>
        internal static string ThereIsNoStation {
            get {
                return ResourceManager.GetString("ThereIsNoStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track &apos;{0}&apos; is not in station &apos;{1}&apos;..
        /// </summary>
        internal static string TheTrackIsItNotInStation {
            get {
                return ResourceManager.GetString("TheTrackIsItNotInStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Train {1} has no times at stations..
        /// </summary>
        internal static string TrainHasNoCalls {
            get {
                return ResourceManager.GetString("TrainHasNoCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Train {1} does not pass station {2}..
        /// </summary>
        internal static string TrainHasNoCallsAtStation {
            get {
                return ResourceManager.GetString("TrainHasNoCallsAtStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Train {1} has overlapping times at {2}..
        /// </summary>
        internal static string TrainHasOverlappingTimesAtStation {
            get {
                return ResourceManager.GetString("TrainHasOverlappingTimesAtStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: SubType {1} is not supported. Please, contact developer if you are missing a type..
        /// </summary>
        internal static string UnsupportedSubType {
            get {
                return ResourceManager.GetString("UnsupportedSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: Type {1} is not supported. Please, contact developer if you are missing a type..
        /// </summary>
        internal static string UnsupportedType {
            get {
                return ResourceManager.GetString("UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use loco {0}..
        /// </summary>
        internal static string UseLoco {
            get {
                return ResourceManager.GetString("UseLoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use loco {0}, classes {1}..
        /// </summary>
        internal static string UseLocoClasses {
            get {
                return ResourceManager.GetString("UseLocoClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet {0} not found..
        /// </summary>
        internal static string WorksheetNotFound {
            get {
                return ResourceManager.GetString("WorksheetNotFound", resourceCulture);
            }
        }
    }
}
